services:
  spring-boot:
    container_name: spring-boot
    image: spring-boot:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src:/app/src 
      - ./target:/app/target 
      - ~/.m2:/root/.m2 
    # environment:
    #   - JAVA_OPTS=-Dspring.devtools.restart.enabled=true
    ports:
      - "8080:8080" 
